
local ignoreNames = {
    -- Sementes
    ["Carrot"] = true,
    ["Strawberry"] = true,
    ["Blueberry"] = true,
    ["Orange Tulip"] = true,
    ["Tomato"] = true,
    ["Corn"] = true,
    ["Daffodil"] = true,
    ["Watermelon"] = true,
    ["Pumpkin"] = true,
    ["Apple"] = true,
    ["Bamboo"] = true,
    ["Coconut"] = true,
    ["Cactus"] = true,
    ["Dragon Fruit"] = true,
    ["Mango"] = true,
    ["Grape"] = true,
    ["Mushroom"] = true,
    ["Pepper"] = true,
    ["Cacao"] = true,
    ["Beanstalk"] = true,
    ["Ember Lily"] = true,
    ["Sugar Apple"] = true,

    -- Gears
    ["Watering Can"] = true,
    ["Trowel"] = true,
    ["Recall Wrench"] = true,
    ["Basic Sprinkler"] = true,
    ["Advanced Sprinkler"] = true,
    ["Godly Sprinkler"] = true,
    ["Lightning Rod"] = true,
    ["Master Sprinkler"] = true,
    ["Cleaning Spray"] = false,
    ["Favorite Tool"] = false,
    ["Harvest Tool"] = false,
    ["Friendship Pot"] = false,
}
