local ignoreNames = {
    -- Sementes
    ["Carrot"] = true,
    ["Strawberry"] = true,
    ["Blueberry"] = true,
    ["Tomato"] = true,
    ["Cauliflower"] = true,
    ["Watermelon"] = true,
    ["Green Apple"] = true,
    ["Avocado"] = true,
    ["Banana"] = true,
    ["Pineapple"] = true,
    ["Kiwi"] = true,
    ["Bell Pepper"] = true,
    ["Prickly Pear"] = true,
    ["Loquat"] = true,
    ["Feijoa"] = true,
    ["Pitcher Plant"] = true,
    ["Sugar Apple"] = true,

    -- Gears
    ["Watering Can"] = true,
    ["Trowel"] = true,
    ["Recall Wrench"] = true,
    ["Basic Sprinkler"] = true,
    ["Advanced Sprinkler"] = true,
    ["Godly Sprinkler"] = true,
    ["Lightning Rod"] = true,
    ["Master Sprinkler"] = true,
    ["Cleaning Spray"] = false,
    ["Favorite Tool"] = false,
    ["Harvest Tool"] = false,
    ["Friendship Pot"] = false,
}
