Values = {
  -- Common
  "None",
  "Carrot",
  "Strawberry",
  "Lavender",

  -- Uncommon
  "Blueberry",
  "Chocolate Carrot",
  "Orange Tulip",
  "Pink Tulip",
  "Mint",
  "Moonflower",
  "Glowshroom",
  "Daffodil",
  "Bee Balm",
  "Red Lollipop",
  "Blue Lollipop",
  "Dezen",

  -- Rare
  "Tomato",
  "Corn",
  "Cauliflower",
  "Pear",
  "Raspberry",
  "Wild Carrot",
  "Firefly Fern",
  "Lavender",
  "Manuka Flower",
  "Noble Flower",
  "Candy Sunflower",
  "Nightshade",
  "Dandelion",
  "Stonebite",
  "Crocus",
  "Rose",
  "Peace Lily",
  "Horsetail",

  -- Legendary
  "Watermelon",
  "Pumpkin",
  "Apple",
  "Green Apple",
  "Banana",
  "Avocado",
  "Bamboo",
  "Starfruit",
  "Cantaloupe",
  "Peach",
  "Pineapple",
  "Nectarine",
  "Lingonberry",
  "Blood Banana",
  "Lumira",
  "Moon Melon",
  "Moonglow",
  "Kiwi",
  "Suncoil",
  "Rosy Delight",
  "Cocovine",
  "Traveler's Fruit",
  "Cherry Blossom",
  "Soul Fruit",
  "Eggplant",
  "Passionfruit",
  "Bendboo",
  "Amber Spine",
  "Enkaku",
  "Sakura Bush",
  "Lucky Bamboo",

  -- Mythical
  "Coconut",
  "Cactus",
  "Dragon Fruit",
  "Mango",
  "Feijoa",
  "Grand Volcania",
  "Boneboo",
  "Horned Dinoshroom",
  "Aloe Vera",
  "Celestiberry",
  "Moon Mango",
  "Trail Fruit",
  "Sugar Apple",
  "Ember Lily",
  "Burning Bud",
  "Pink Lily",
  "Parasol Flower",
  "Honeysuckle",

  -- Divine
  "Pepper",
  "Cacao",
  "Grape",
  "Mushroom",
  "Maple Apple",
  "Hinomai",
  "Lotus",
  "Venus Fly Trap",
  "Moon Blossom",
  "Candy Blossom",
  "Hive Fruit",
  "Dragon Pepper",
  "Pitcher Plant",
  "Sunflower",

  -- Prismatic
  "Beanstalk",
  "Giant Pinecone",
  "Fossilight",
  "Blood Banana",
  "Bone Blossom",
  "Elephant Ears",
  "Tranquil Bloom"
}

return Values
